model: 
  CNN: 
    name: vitb16
    class_num: 15
    pretrain: vit_b_16-c867db91.pth
  encoder:
  decoder:

dataset:
  train_path: ./data/train
  val_path: ./data/test

train:
  epoch: 300
  leaning_rate: 0.001
  criterion: CE
  optimizer: SGD
  